---
  - name: create plugins directory
    file:
      path: "{{ jenkins_plugins_path }}"
      state: directory
      owner: jenkins
      group: jenkins

  - name: download plugins
    get_url:
      url: http://updates.jenkins-ci.org/latest/{{ item }}.hpi
      dest: "{{ jenkins_plugins_path }}/{{ item }}.hpi"
      owner: jenkins
      group: jenkins
    with_items:
      - ace-editor
      - antisamy-markup-formatter
      - ant
      - bouncycastle-api
      - branch-api
      - build-timeout
      - cloudbees-folder
      - credentials
      - credentials-binding
      - display-url-api
      - durable-task
      - email-ext
      - external-monitor-job
      - git-client
      - github-api
      - github-branch-source
      - github
      - github-organization-folder
      - git
      - git-server
      - gradle
      - handlebars
      - icon-shim
      - jquery-detached
      - junit
      - ldap
      - mailer
      - mapdb-api
      - matrix-auth
      - matrix-project
      - momentjs
      - pam-auth
      - pipeline-build-step
      - pipeline-graph-analysis
      - pipeline-input-step
      - pipeline-milestone-step
      - pipeline-rest-api
      - pipeline-stage-step
      - pipeline-stage-view
      - plain-credentials
      - resource-disposer
      - scm-api
      - script-security
      - ssh-credentials
      - ssh-slaves
      - structs
      - subversion
      - timestamper
      - token-macro
      - windows-slaves
      - workflow-aggregator
      - workflow-api
      - workflow-basic-steps
      - workflow-cps-global-lib
      - workflow-cps
      - workflow-durable-task-step
      - workflow-job
      - workflow-multibranch
      - workflow-scm-step
      - workflow-step-api
      - workflow-support
      - ws-cleanup

  - name: restart jenkins
    service:
      name: jenkins
      state: restarted