---
  - name: install ansible-lint dependencies (via pip)
    pip:
      name: "{{ item }}"
    with_items:
      - markupsafe
      - PyYAML

  - name: install ansible-lint dependencies (via apt-get)
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - python-keyczar
      - python-httplib2
      - python-jinja2
      - python-paramiko
      - python-setuptools
      - python-six
      - python-dev
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: install ansible-lint
    pip:
      name: ansible-lint